/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-secondary": "#283500",
        "error-container": "#93000a",
        "inverse-surface": "#e3e2e2",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#161e00",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-container": "#7e7d7d",
        "on-surface-variant": "#c4c7c7",
        "on-tertiary-fixed-variant": "#852400",
        "on-primary-fixed-variant": "#474646",
        "error": "#ffb4ab",
        "surface-container-low": "#1a1c1c",
        "on-secondary-container": "#556d00",
        "tertiary-fixed-dim": "#ffb59e",
        "inverse-on-surface": "#2f3131",
        "tertiary-fixed": "#ffdbd0",
        "on-background": "#e3e2e2",
        "secondary-container": "#c3f400",
        "on-secondary-fixed-variant": "#3c4d00",
        "on-surface": "#e3e2e2",
        "background": "#121414",
        "primary": "#c8c6c5",
        "surface-container-high": "#292a2a",
        "secondary": "#ffffff",
        "surface-container": "#1e2020",
        "on-error": "#690005",
        "on-tertiary": "#5e1700",
        "secondary-fixed": "#c3f400",
        "primary-container": "#121212",
        "outline-variant": "#444748",
        "outline": "#8e9192",
        "secondary-fixed-dim": "#abd600",
        "surface-variant": "#343535",
        "on-tertiary-container": "#e44400",
        "on-primary": "#313030",
        "surface": "#121414",
        "tertiary-container": "#290600",
        "primary-fixed": "#e5e2e1",
        "inverse-primary": "#5f5e5e",
        "surface-container-highest": "#343535",
        "surface-container-lowest": "#0d0e0f",
        "surface-bright": "#383939",
        "surface-dim": "#121414",
        "tertiary": "#ffb59e",
        "surface-tint": "#c8c6c5",
        "on-tertiary-fixed": "#3a0b00"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "unit": "8px",
        "stack-lg": "64px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "container-max": "1440px",
        "stack-sm": "16px",
        "margin-desktop": "64px",
        "stack-md": "32px"
      },
      "fontFamily": {
        "display-sm": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "label-sm": ["Geist"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Montserrat"],
        "body-lg": ["Inter"],
        "display-lg": ["Montserrat"],
        "label-bold": ["Geist"]
      },
      "fontSize": {
        "display-sm": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "800"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-bold": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
